apiVersion: v1
kind: Pod
metadata:
  name: vosk-server-pod
  labels:
    app: vosk-server
spec:
  containers:
  - name: vosk-server-container
    image: alphacep/kaldi-vosk-server:latest
    env:
    - name: MODEL_VERSION
      value: "0.22"
    command: [ "sh", "-c", "
      mkdir -p /opt/vosk-model-en && \
      cd /opt/vosk-model-en && \
      wget -q http://alphacephei.com/kaldi/models/vosk-model-en-us-${MODEL_VERSION}.zip && \
      unzip vosk-model-en-us-${MODEL_VERSION}.zip && \
      mv vosk-model-en-us-${MODEL_VERSION} model && \
      rm -rf vosk-model-en-us-${MODEL_VERSION}.zip && \
      python3 /opt/vosk-server/websocket/asr_server.py /opt/vosk-model-en/model
    " ]
    ports:
    - containerPort: 2700
